import type { Metadata } from "next";
import { Inter, JetBrains_Mono } from "next/font/google";
import "./globals.css";
import { ClerkProvider } from "@clerk/nextjs";
import { Toaster } from "sonner";
import { NextSSRPlugin } from "@uploadthing/react/next-ssr-plugin";
import { extractRouterConfig } from "uploadthing/server";
import { fluxUploadRouter } from "./api/uploadthing/core";
import { dark } from "@clerk/themes";
import { QueryProvider } from "@/providers/query-provider";
import { ModalProvider } from "@/providers/modal-provider";
import { CurrentProfileProvider } from "@/providers/current-profile-provider";
import { getCurrentProfile } from "@/data/profile";
const inter = Inter({
	variable: "--font-inter",
	subsets: ["latin"],
	display: "swap",
});

const jetBrainsMono = JetBrains_Mono({
	variable: "--font-jetBrains-mono",
	subsets: ["latin"],
	display: "swap",
});

export const metadata: Metadata = {
	title: "Create Next App",
	description: "Generated by create next app",
};

export default async function RootLayout({
	children,
}: Readonly<{
	children: React.ReactNode;
}>) {
	const profile = await getCurrentProfile();
	return (
		<ClerkProvider
			appearance={{
				theme: dark,
			}}
		>
			<html lang="en" className="dark" data-theme="dark" suppressHydrationWarning>
				<body className={`${inter.variable} ${jetBrainsMono.variable} antialiased bg-background text-foreground`}>
					<QueryProvider>
						<CurrentProfileProvider profile={profile}>
							<NextSSRPlugin routerConfig={extractRouterConfig(fluxUploadRouter)} />
							<Toaster theme="dark" position="bottom-right" />
							<ModalProvider />
							{children}
						</CurrentProfileProvider>
					</QueryProvider>
				</body>
			</html>
		</ClerkProvider>
	);
}
